management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
    enabled-by-default: 'true'
  endpoint:
    metrics:
      enabled: 'true'
    info:
      enabled: 'true'
eureka:
  instance:
    instance-id: ${DOMAIN_NAME:microservice-alimentation.herokuapp.com}
    healthCheckUrl: https://${eureka.hostname}/actuator/health
    homePageUrl: https://${eureka.hostname}/
    hostname: ${DOMAIN_NAME:microservice-alimentation.herokuapp.com}
    statusPageUrl: https://${eureka.hostname}/actuator/info
  client:
    service-url:
      defaultZone: http://52.73.98.2:8099/eureka/
spring:
  boot:
    admin:
      client:
        instance:
          service-base-url: https://${DOMAIN_NAME:microservice-alimentation.herokuapp.com}
        url: http://34.232.227.255:8086
  profiles: ${PROFILE_NAME:default}
  datasource:
    driverClassName: org.postgresql.Driver
    password: Buele30.03.1997LES
    username: postgres
    url: jdbc:postgresql://db.ssnqugygamsjojwjqqjj.supabase.co/postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
  data:
    jpa:
      repositories:
        enabled: 'true'
  application:
    name: aliments-service
server:
  port: ${port:8080}
  error:
    incluse-binding-errors: always
    include-message: always
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5P} %m%n'