server:
  error:
    include-binding-errors: always
    include-message: always
  port: ${port:8080}
spring:
  data:
    mongodb:
      database: Registers
      uri: mongodb+srv://aracely10:aracely1008@cluster0.biago.mongodb.net/?retryWrites=true&w=majority
    application:
      name: control-service
  boot:
    admin:
      client:
        instance:
          service-base-url: https://${DOMAIN_NAME:control-service.herokuapp.com}
eureka:
  instance:
    instance-id: ${DOMAIN_NAME:control-service.herokuapp.com}
    healthCheckUrl: https://${eureka.hostname}/actuator/health
    homePageUrl: https://${eureka.hostname}/
    hostname: ${DOMAIN_NAME:control-service.herokuapp.com}
    statusPageUrl: https://${eureka.hostname}/actuator/info
  client:
    service-url:
      defaultZone: http://52.73.98.2:8099/eureka/
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5P} %m%n'
management:
  endpoints:
    web:
      exposure:
        include: "*"