server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://52.73.98.2:8099/eureka/

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://54.87.30.242:8081
          predicates:
            - Path=/user/**
        - id: aliments-service
          uri: https://microservice-alimentation.herokuapp.com
          predicates:
            - Path=/alimentation/**
        - id: pill-service
          uri: lb://pill-service
          predicates:
            - Path=/pills/**
        - id: tratamientos-service
          uri: lb://tratamientos-service
          predicates:
            - Path=/treatement/**
        - id: productos-service
          uri: https://productosmicroapi.herokuapp.com
          predicates:
            - Path=/fridge/**
        - id: actividadfisica-service
          uri: lb://actividadfisica-service
          predicates:
            - Path=/activity/**
        - id: control-service
          uri: http://control-service.herokuapp.com
          predicates:
            - Path=/control/**
        - id: measure-service
          uri: http://measure-service.herokuapp.com
          predicates:
            - Path=/measures/**
