
server:
  port: ${PORT:8084}
  servlet:
    application-display-name : pill-service
  application:
    name : pill-service

spring:
  data:
    mongodb:
      uri : mongodb+srv://danielseaman:betelgeuse@cluster0.0pwrpay.mongodb.net/smartdrugsdb?retryWrites=true&w=majority

eureka:
  client:
    serviceUrl:
      defaultZone : http://52.73.98.2:8099/eureka/

Feign:
  hystrix:
    enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"