
server:
  port: ${PORT:8084}
  servlet:
    application-display-name : pill-service
  application:
    name : pill-service

spring:
  data:
    mongodb:
      uri : mongodb+srv://danielseaman:betelgeuse@cluster0.0pwrpay.mongodb.net/smartdrugsdb?retryWrites=true&w=majority
  boot:
    admin:
      client:
        instance:
          service-base-url=https: //${DOMAIN_NAME:pillservice.herokuapp.com}

eureka:
  client:
    serviceUrl:
      defaultZone : http://52.73.98.2:8099/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: "true"
  endpoint:
    metrics:
      enabled: "true"
    info:
      enabled: "true"